#! /usr/bin/env bash

# Update script
# Author: Ciara Martin

info() {
  tput setaf 5; printf "==> "; tput sgr0; echo "$*"
}

if  [[ "$( uname -s )" = "Darwin" ]] > /dev/null 2>&1; then
  info "Updating brew"
  brew update
  echo ""
  info "Updating brew apps"
  brew upgrade
  echo ""
  info "Updating brew Mac apps"
  brew upgrade --greedy
  echo ""
  info "Cleaning up brew apps"
  brew cleanup -s
  echo ""
  info "Installing missing dependencies"
  brew missing
  echo ""
  info "Removing unneeded apps"
  brew autoremove
  echo ""
  info "Checking brew"
  brew doctor
fi

if [ -f /etc/os-release ]; then
  source /etc/os-release
  os="${ID}"
  os_family="${ID_LIKE}"
  case "${os}" in
    debian | ubuntu | raspbian | pop )
      info "Updating apt cache"
      sudo apt update
      info "Installing updates"
      sudo apt upgrade
      info "Removing unneeded apps"
      sudo apt autoremove
      ;;
  esac

  case "${os_family}" in
    *debian* | *ubuntu* )
      info "Updating apt cache"
      sudo apt update
      info "Installing updates"
      sudo apt upgrade
      info "Removing unneeded apps"
      sudo apt autoremove
      ;;
    *arch* )
      sudo pacman -Syu
      ;;
    *rhel* | *fedora* )
      if (command -v dnf > /dev/null 2>&1); then
        sudo dnf update
      else
        sudo yum update
      fi
      ;;
    *opensuse* | *suse* )
      sudo zypper refresh
      sudo zypper update
      ;;
  esac
fi
