#! /usr/bin/env bash

# Update script
# Author: Ciara Martin

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Define functions
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

check() {
  # Purpose:  Display task status, log result & exit on error
  # Usage:    check $? "Task name"
  if [ "$1" -eq 0 ]; then
    printf "\n🟢  %s successful\n\n" "$2"
  else
    printf "\n🔴  %s failed\n\n" "$2"
    exit 1
  fi
}

info() {
  # Purpose:  Displays an info message & outputs to logfile
  # Usage:    info "Message"
  printf "\n🔵  %s\n\n" "$1"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#   Main
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if  [[ "$( uname -s )" = "Darwin" ]] > /dev/null 2>&1; then
  info "Updating brew"
  brew update
  check $? "Brew update"

  info "Upgrading brew apps"
  brew upgrade --formula
  check $? "Brew app upgrade"

  info "Upgrading brew Mac apps"
  brew upgrade --cask --greedy
  check $? "Brew Mac app upgrade"

  info "Cleaning up brew"
  brew cleanup -s
  check $? "Brew cleanup"

  info "Installing missing dependencies"
  brew missing
  check $? "Missing dependency install"

  info "Checking brew"
  brew doctor
  check $? "Brew check"
fi

if [ -f /etc/os-release ]; then
  source /etc/os-release
  os="${ID}"
  os_family="${ID_LIKE}"
  case "${os}" in
    debian | ubuntu | raspbian | pop )
      info "Updating apt cache"
      sudo apt update
      check $? "apt update"

      info "Upgrading apt apps"
      sudo apt upgrade
      check $? "apt upgrade"

      info "Autoremove apt apps"
      sudo apt autoremove
      check $? "apt autoremove"
      ;;
  esac

  case "${os_family}" in
    *debian* | *ubuntu* )
      info "Updating apt cache"
      sudo apt update
      check $? "apt update"

      info "Upgrading apt apps"
      sudo apt upgrade
      check $? "apt upgrade"

      info "Autoremove apt apps"
      sudo apt autoremove
      check $? "apt autoremove"
      ;;
    *arch* )
      info "Updating pacman apps"
      sudo pacman -Syu
      check $? "pacman update"
      ;;
    *rhel* | *fedora* )
      if (command -v dnf > /dev/null 2>&1); then
        info "Updating dnf apps"
        sudo dnf update
        check $? "dnf update"
      else
        info "Updating yum apps"
        sudo yum update
        check $? "yum update"
      fi
      ;;
    *opensuse* | *suse* )
      info "Refreshing zypper cache"
      sudo zypper refresh
      check $? "zypper refresh"

      info "Updating zypper apps"
      sudo zypper update
      check $? "zypper update"
      ;;
  esac
fi
