#!/usr/bin/env bash

if [ $(uname -s) = "Darwin" ]; then
    if test -n "$1"; then
        name="$1"
        echo "Setting Hostname to: $name"
    else
        read -p "Enter new Hostname: " name
    fi
    # Set computer name (as done via System Preferences → Sharing)
    sudo scutil --set ComputerName "$name"
    sudo scutil --set HostName "$name"
    sudo scutil --set LocalHostName "$name"
    sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$name"
    echo "Done"
else
    echo "This script runs under OS X only."
fi
