#!/usr/bin/env bash

if [ $(uname -s) = "Darwin" ]; then

    # Get script directory
    SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, resolve it
    done
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

    # Ask for the administrator password upfront
    sudo -v

    # Keep-alive: update existing `sudo` time stamp until we are finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

        ###############################################################################
        # General UI/UX                                                               #
        ###############################################################################

        # Disable the sound effects on boot
        sudo nvram SystemAudioVolume=" "

        # Disable transparency in the menu bar and elsewhere on Yosemite
        defaults write com.apple.universalaccess reduceTransparency -bool true

        # Set highlight color to grey
        defaults write NSGlobalDomain AppleHighlightColor -string "0.700000 0.700000 0.700000"

        # Set sidebar icon size to medium
        defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 2

        # Only show scrollbars when scrolling
        defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"
        # Possible values: `WhenScrolling`, `Automatic` and `Always`

        # Increase window resize speed for Cocoa applications
        defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

        # Expand save panel by default
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

        # Expand print panel by default
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

        # Save to disk (not to iCloud) by default
        defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

        # Automatically quit printer app once the print jobs complete
        defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

        # Disable the “Are you sure you want to open this application?” dialog
        defaults write com.apple.LaunchServices LSQuarantine -bool false

        # Disable Resume system-wide
        defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

        # Disable automatic termination of inactive apps
        defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

        # Disable the crash reporter
        defaults write com.apple.CrashReporter DialogType -string "none"

        # Check for software updates daily, not just once per week
        defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

        ###############################################################################
        # SSD-specific tweaks                                                         #
        ###############################################################################

        # Disable hibernation (speeds up entering sleep mode)
        sudo pmset -a hibernatemode 0

        # Remove the sleep image file to save disk space
        sudo rm /private/var/vm/sleepimage
        # Create a zero-byte file instead…
        sudo touch /private/var/vm/sleepimage

        # Disable the sudden motion sensor as it’s not useful for SSDs
        sudo pmset -a sms 0

        ###############################################################################
        # Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
        ###############################################################################

        # Trackpad: enable tap to click for this user and for the login screen
        defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
        defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
        defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

        # Trackpad: map bottom right corner to right-click
        defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
        defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
        defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
        defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

        # Enable “natural” (Lion-style) scrolling
        defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true

        # Enable full keyboard access for all controls
        # (e.g. enable Tab in modal dialogs)
        defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

        # Use scroll gesture with the Ctrl (^) modifier key to zoom
        defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
        defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
        # Follow the keyboard focus while zoomed in
        defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true

        # Disable press-and-hold for keys in favor of key repeat
        defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

        # Set a blazingly fast keyboard repeat rate
        defaults write NSGlobalDomain KeyRepeat -int 0

        # Set language and text formats
        # Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
        # `Inches`, `en_GB` with `en_US`, and `true` with `false`.
        defaults write NSGlobalDomain AppleLanguages -array "en"
        defaults write NSGlobalDomain AppleLocale -string "en_ie"
        defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
        defaults write NSGlobalDomain AppleMetricUnits -bool true

        # Set the timezone; see `sudo systemsetup -listtimezones` for other values
        sudo systemsetup -settimezone "Europe/Dublin" > /dev/null

        # Disable auto-correct
        defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

        ###############################################################################
        # Screen                                                                      #
        ###############################################################################

        # Require password immediately after sleep or screen saver begins
        defaults write com.apple.screensaver askForPassword -int 1
        defaults write com.apple.screensaver askForPasswordDelay -int 0

        # Save screenshots to the desktop
        defaults write com.apple.screencapture location -string "${HOME}/Desktop"

        # Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
        defaults write com.apple.screencapture type -string "png"

        # Disable shadow in screenshots
        defaults write com.apple.screencapture disable-shadow -bool true

        # Enable subpixel font rendering on non-Apple LCDs
        defaults write NSGlobalDomain AppleFontSmoothing -int 2

        ###############################################################################
        # Finder                                                                      #
        ###############################################################################

        # Finder: disable window animations and Get Info animations
        defaults write com.apple.finder DisableAllAnimations -bool true

        # Set Home as the default location for new Finder windows
        # For other paths, use `PfLo` and `file:///full/path/here/`
        defaults write com.apple.finder NewWindowTarget -string "PfLo"
        defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

        # Show icons for hard drives, servers, and removable media on the desktop
        defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
        defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
        defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
        defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

        # Finder: show all filename extensions
        defaults write NSGlobalDomain AppleShowAllExtensions -bool true

        # Finder: show status bar
        defaults write com.apple.finder ShowStatusBar -bool true

        # Finder: show path bar
        defaults write com.apple.finder ShowPathbar -bool true

        # When performing a search, search the current folder by default
        defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

        # Disable the warning when changing a file extension
        defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

        # Avoid creating .DS_Store files on network volumes
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

        # Disable disk image verification
        defaults write com.apple.frameworks.diskimages skip-verify -bool true
        defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
        defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

        # Automatically open a new Finder window when a volume is mounted
        defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
        defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
        defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

        # Show item info near icons on the desktop and in other icon views
        /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist

        # Show item info to the right of the icons on the desktop
        /usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist

        # Enable snap-to-grid for icons on the desktop and in other icon views
        /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

        # Increase grid spacing for icons on the desktop and in other icon views
        /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:gridSpacing 96" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:gridSpacing 96" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:gridSpacing 96" ~/Library/Preferences/com.apple.finder.plist

        # Increase the size of icons on the desktop and in other icon views
        /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:iconSize 40" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:iconSize 40" ~/Library/Preferences/com.apple.finder.plist
        /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:iconSize 40" ~/Library/Preferences/com.apple.finder.plist

        # Use column view in all Finder windows by default
        # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
        defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

        # Disable the warning before emptying the Trash
        defaults write com.apple.finder WarnOnEmptyTrash -bool false

        # Empty Trash securely by default
        # defaults write com.apple.finder EmptyTrashSecurely -bool true

        # Enable AirDrop over Ethernet and on unsupported Macs running Lion
        defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

        # Show the ~/Library folder
        chflags nohidden ~/Library

        # Expand the following File Info panes:
        # “General”, “Open with”, and “Sharing & Permissions”
        defaults write com.apple.finder FXInfoPanesExpanded -dict \
            General -bool true \
            OpenWith -bool true \
            Privileges -bool true

        ###############################################################################
        # Dock, Dashboard, and hot corners                                            #
        ###############################################################################

        # Set the icon size of Dock items to 36 pixels
        defaults write com.apple.dock tilesize -int 36

        # Change minimize/maximize window effect
        defaults write com.apple.dock mineffect -string "scale"

        # Minimize windows into their application’s icon
        defaults write com.apple.dock minimize-to-application -bool true

        # Enable spring loading for all Dock items
        defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

        # Don't show indicator lights for open applications in the Dock
        defaults write com.apple.dock show-process-indicators -bool false

        # Wipe all (default) app icons from the Dock
        # This is only really useful when setting up a new Mac, or if you don’t use
        # the Dock to launch apps.
        defaults write com.apple.dock persistent-apps -array

        # Don’t animate opening applications from the Dock
        defaults write com.apple.dock launchanim -bool false

        # Speed up Mission Control animations
        defaults write com.apple.dock expose-animation-duration -float 0.1

        # Don’t group windows by application in Mission Control
        # (i.e. use the old Exposé behavior instead)
        defaults write com.apple.dock expose-group-by-app -bool false

        # Disable Dashboard
        defaults write com.apple.dashboard mcx-disabled -bool true

        # Don’t show Dashboard as a Space
        defaults write com.apple.dock dashboard-in-overlay -bool true

        # Don’t automatically rearrange Spaces based on most recent use
        defaults write com.apple.dock mru-spaces -bool false

        # Remove the auto-hiding Dock delay
        defaults write com.apple.dock autohide-delay -float 0

        # Remove the animation when hiding/showing the Dock
        defaults write com.apple.dock autohide-time-modifier -float 0

        # Automatically hide and show the Dock
        defaults write com.apple.dock autohide -bool true

        # Don't make Dock icons of hidden applications translucent
        defaults write com.apple.dock showhidden -bool false

        # Hot corners
        # Possible values:
        #  0: no-op
        #  2: Mission Control
        #  3: Show application windows
        #  4: Desktop
        #  5: Start screen saver
        #  6: Disable screen saver
        #  7: Dashboard
        # 10: Put display to sleep
        # 11: Launchpad
        # 12: Notification Center
        # Top left screen corner → Mission Control
        defaults write com.apple.dock wvous-tl-corner -int 2
        defaults write com.apple.dock wvous-tl-modifier -int 0
        # Top right screen corner → Notification Center
        defaults write com.apple.dock wvous-tr-corner -int 12
        defaults write com.apple.dock wvous-tr-modifier -int 0
        # Bottom left screen corner → Start screen saver
        defaults write com.apple.dock wvous-bl-corner -int 5
        defaults write com.apple.dock wvous-bl-modifier -int 0

        ###############################################################################
        # Safari & WebKit                                                             #
        ###############################################################################

        # Privacy: don’t send search queries to Apple
        defaults write com.apple.Safari UniversalSearchEnabled -bool false
        defaults write com.apple.Safari SuppressSearchSuggestions -bool true

        # Press Tab to highlight each item on a web page
        defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
        defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

        # Show the full URL in the address bar (note: this still hides the scheme)
        defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

        # Set Safari’s home page to `about:blank` for faster loading
        defaults write com.apple.Safari HomePage -string "about:blank"

        # Prevent Safari from opening ‘safe’ files automatically after downloading
        defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

        # Allow hitting the Backspace key to go to the previous page in history
        defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled -bool true

        # Hide Safari’s bookmarks bar by default
        defaults write com.apple.Safari ShowFavoritesBar -bool false

        # Hide Safari’s sidebar in Top Sites
        defaults write com.apple.Safari ShowSidebarInTopSites -bool false

        # Disable Safari’s thumbnail cache for History and Top Sites
        defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2

        # Enable Safari’s debug menu
        defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

        # Make Safari’s search banners default to Contains instead of Starts With
        defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false

        # Remove useless icons from Safari’s bookmarks bar
        defaults write com.apple.Safari ProxiesInBookmarksBar "()"

        # Enable the Develop menu and the Web Inspector in Safari
        defaults write com.apple.Safari IncludeDevelopMenu -bool true
        defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
        defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

        # Add a context menu item for showing the Web Inspector in web views
        defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

        ###############################################################################
        # Mail                                                                        #
        ###############################################################################

        # Disable send and reply animations in Mail.app
        defaults write com.apple.mail DisableReplyAnimations -bool true
        defaults write com.apple.mail DisableSendAnimations -bool true

        # Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
        defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

        # Add the keyboard shortcut ⌘ + Enter to send an email in Mail.app
        defaults write com.apple.mail NSUserKeyEquivalents -dict-add "Send" -string "@\\U21a9"

        # Display emails in threaded mode, sorted by date (oldest at the top)
        defaults write com.apple.mail DraftsViewerAttributes -dict-add "DisplayInThreadedMode" -string "yes"
        defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortedDescending" -string "yes"
        defaults write com.apple.mail DraftsViewerAttributes -dict-add "SortOrder" -string "received-date"

        # Disable inline attachments (just show the icons)
        defaults write com.apple.mail DisableInlineAttachmentViewing -bool true

        ###############################################################################
        # Spotlight                                                                   #
        ###############################################################################

        # Disable Spotlight indexing for any volume that gets mounted and has not yet
        # been indexed before.
        sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"
        # Change indexing order and disable some search results
        # Yosemite-specific search results (remove them if your are using OS X 10.9 or older):
        #   MENU_DEFINITION
        #   MENU_CONVERSION
        #   MENU_EXPRESSION
        #   MENU_SPOTLIGHT_SUGGESTIONS (send search queries to Apple)
        #   MENU_WEBSEARCH             (send search queries to Apple)
        #   MENU_OTHER
        defaults write com.apple.spotlight orderedItems -array \
            '{"enabled" = 1;"name" = "APPLICATIONS";}' \
            '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
            '{"enabled" = 1;"name" = "DIRECTORIES";}' \
            '{"enabled" = 1;"name" = "PDF";}' \
            '{"enabled" = 1;"name" = "DOCUMENTS";}' \
            '{"enabled" = 1;"name" = "IMAGES";}' \
            '{"enabled" = 1;"name" = "MUSIC";}' \
            '{"enabled" = 1;"name" = "PRESENTATIONS";}' \
            '{"enabled" = 1;"name" = "FONTS";}' \
            '{"enabled" = 1;"name" = "SPREADSHEETS";}' \
            '{"enabled" = 1;"name" = "MOVIES";}' \
            '{"enabled" = 0;"name" = "MESSAGES";}' \
            '{"enabled" = 0;"name" = "CONTACT";}' \
            '{"enabled" = 0;"name" = "EVENT_TODO";}' \
            '{"enabled" = 0;"name" = "BOOKMARKS";}' \
            '{"enabled" = 0;"name" = "SOURCE";}' \
            '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
            '{"enabled" = 0;"name" = "MENU_OTHER";}' \
            '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
            '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
            '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
            '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
        # Load new settings before rebuilding the index
        killall mds > /dev/null 2>&1
        # Make sure indexing is enabled for the main volume
        sudo mdutil -i on / > /dev/null
        # Rebuild the index from scratch
        sudo mdutil -E / > /dev/null

        ###############################################################################
        # Terminal & iTerm 2                                                          #
        ###############################################################################

        # Only use UTF-8 in Terminal.app
        defaults write com.apple.terminal StringEncodings -array 4

        # Don’t display the annoying prompt when quitting iTerm
        defaults write com.googlecode.iterm2 PromptOnQuit -bool false

        ###############################################################################
        # Time Machine                                                                #
        ###############################################################################

        # Prevent Time Machine from prompting to use new hard drives as backup volume
        defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

        # Disable local Time Machine backups
        hash tmutil &> /dev/null && sudo tmutil disablelocal

        ###############################################################################
        # Activity Monitor                                                            #
        ###############################################################################

        # Show the main window when launching Activity Monitor
        defaults write com.apple.ActivityMonitor OpenMainWindow -bool true

        # Show all processes in Activity Monitor
        defaults write com.apple.ActivityMonitor ShowCategory -int 0

        # Sort Activity Monitor results by CPU usage
        defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
        defaults write com.apple.ActivityMonitor SortDirection -int 0

        ###############################################################################
        # Google Chrome                                                               #
        ###############################################################################

        # Use the system-native print preview dialog
        defaults write com.google.Chrome DisablePrintPreview -bool true

        # Expand the print dialog by default
        defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true

       ###############################################################################
        # Kill affected applications                                                  #
        ###############################################################################

        for app in "Activity Monitor" "cfprefsd" "Dock" "Finder" "Google Chrome" \
            "Mail" "Safari" "SystemUIServer" "Terminal" ; do
        killall "${app}" > /dev/null 2>&1
    done

    # Set hostname
    source $DIR/rename
    # Install applications using brew
    source $DIR/brew-apps
    # Link dotfiles using RCM and load new config
    echo -e "\nLinking dotfiles to your home directory ..."
    rcup -v -d ~/.dotfiles -x "*:*osx*" -x "*:*linux*" -x "*:*README*"
    source ~/.bashrc

    # Setup Vim
    echo -e "\nSetting up Vim ..."
    if [ ! -d ~/.vim/bundle/base16-vim ]; then
        git clone https://github.com/chriskempson/base16-vim.git ~/.vim/bundle/base16-vim
    fi
    if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    fi
    vim +PluginInstall +qall

    echo -e "\nDone. Note that some of these changes require a logout/restart to take effect."
else
    echo "This script runs under OS X only."
fi
