#!/usr/bin/env bash

if [ $(uname -s) = "Darwin" ]; then

    # Get script directory
    SOURCE="${BASH_SOURCE[0]}"
    while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
        DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
        SOURCE="$(readlink "$SOURCE")"
        [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, resolve it
    done
    DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

    # Ask for the administrator password upfront
    sudo -v

    # Keep-alive: update existing `sudo` time stamp until we are finished
    while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

        ###############################################################################
        # General UI/UX                                                               #
        ###############################################################################

        # Disable the sound effects on boot
        sudo nvram SystemAudioVolume=" "

        # Disable transparency in the menu bar and elsewhere on Yosemite
        defaults write com.apple.universalaccess reduceTransparency -bool true

        # Set highlight color to grey
        defaults write NSGlobalDomain AppleHighlightColor -string "0.700000 0.700000 0.700000"

        # Always show scrollbars when scrolling
        defaults write NSGlobalDomain AppleShowScrollBars -string "Always"
        # Possible values: `WhenScrolling`, `Automatic` and `Always`

        # Increase window resize speed for Cocoa applications
        defaults write NSGlobalDomain NSWindowResizeTime -float 0.001

        # Expand save panel by default
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
        defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

        # Expand print panel by default
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
        defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

        # Save to disk (not to iCloud) by default
        defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

        # Automatically quit printer app once the print jobs complete
        defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

        # Disable the “Are you sure you want to open this application?” dialog
        defaults write com.apple.LaunchServices LSQuarantine -bool false

        # Disable Resume system-wide
        defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false

        # Disable automatic termination of inactive apps
        defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true

        # Disable the crash reporter
        defaults write com.apple.CrashReporter DialogType -string "none"

        ###############################################################################
        # SSD-specific tweaks                                                         #
        ###############################################################################

        # Disable hibernation (speeds up entering sleep mode)
        sudo pmset -a hibernatemode 0

        # Remove the sleep image file to save disk space
        sudo rm /private/var/vm/sleepimage
        # Create a zero-byte file instead…
        sudo touch /private/var/vm/sleepimage

        # Disable the sudden motion sensor as it’s not useful for SSDs
        sudo pmset -a sms 0

        ###############################################################################
        # Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
        ###############################################################################

        # Trackpad: enable tap to click for this user and for the login screen
        defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
        defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
        defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

        # Trackpad: map bottom right corner to right-click
        defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
        defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true
        defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
        defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true

        # Enable “natural” (Lion-style) scrolling
        defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true

        # Enable full keyboard access for all controls
        # (e.g. enable Tab in modal dialogs)
        defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

        # Disable press-and-hold for keys in favor of key repeat
        defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

        # Set a blazingly fast keyboard repeat rate
        defaults write NSGlobalDomain KeyRepeat -int 0

        # Set language and text formats
        # Note: if you’re in the US, replace `EUR` with `USD`, `Centimeters` with
        # `Inches`, `en_GB` with `en_US`, and `true` with `false`.
        defaults write NSGlobalDomain AppleLanguages -array "en"
        defaults write NSGlobalDomain AppleLocale -string "en_ie"
        defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
        defaults write NSGlobalDomain AppleMetricUnits -bool true

        # Set the timezone; see `sudo systemsetup -listtimezones` for other values
        sudo systemsetup -settimezone "Europe/Dublin" > /dev/null

        # Disable auto-correct
        defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

        ###############################################################################
        # Screen                                                                      #
        ###############################################################################

        # Require password immediately after sleep or screen saver begins
        defaults write com.apple.screensaver askForPassword -int 1
        defaults write com.apple.screensaver askForPasswordDelay -int 0

        # Save screenshots to the desktop
        defaults write com.apple.screencapture location -string "${HOME}/Desktop"

        # Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
        defaults write com.apple.screencapture type -string "png"

        # Disable shadow in screenshots
        defaults write com.apple.screencapture disable-shadow -bool true

        # Enable subpixel font rendering on non-Apple LCDs
        defaults write NSGlobalDomain AppleFontSmoothing -int 2

        ###############################################################################
        # Finder                                                                      #
        ###############################################################################

        # Finder: disable window animations and Get Info animations
        defaults write com.apple.finder DisableAllAnimations -bool true

        # Set Home as the default location for new Finder windows
        # For other paths, use `PfLo` and `file:///full/path/here/`
        defaults write com.apple.finder NewWindowTarget -string "PfLo"
        defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"

        # Finder: show status bar
        defaults write com.apple.finder ShowStatusBar -bool true

        # Finder: show path bar
        defaults write com.apple.finder ShowPathbar -bool true

        # When performing a search, search the current folder by default
        defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

        # Disable the warning when changing a file extension
        defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

        # Avoid creating .DS_Store files on network volumes
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

        # Disable disk image verification
        defaults write com.apple.frameworks.diskimages skip-verify -bool true
        defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
        defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

        # Automatically open a new Finder window when a volume is mounted
        defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
        defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
        defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

        # Use column view in all Finder windows by default
        # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
        defaults write com.apple.finder FXPreferredViewStyle -string "clmv"

        # Disable the warning before emptying the Trash
        defaults write com.apple.finder WarnOnEmptyTrash -bool false

        # Show the ~/Library folder
        chflags nohidden ~/Library

        # Expand the following File Info panes:
        # “General”, “Open with”, and “Sharing & Permissions”
        defaults write com.apple.finder FXInfoPanesExpanded -dict \
            General -bool true \
            OpenWith -bool true \
            Privileges -bool true

        ###############################################################################
        # Dock, Dashboard, and hot corners                                            #
        ###############################################################################

        # Set the icon size of Dock items to 36 pixels
        defaults write com.apple.dock tilesize -int 36

        # Change minimize/maximize window effect
        defaults write com.apple.dock mineffect -string "scale"

        # Minimize windows into their application’s icon
        defaults write com.apple.dock minimize-to-application -bool true

        # Enable spring loading for all Dock items
        defaults write com.apple.dock enable-spring-load-actions-on-all-items -bool true

        # Don't show indicator lights for open applications in the Dock
        defaults write com.apple.dock show-process-indicators -bool false

        # Wipe all (default) app icons from the Dock
        # This is only really useful when setting up a new Mac, or if you don’t use
        # the Dock to launch apps.
        defaults write com.apple.dock persistent-apps -array

        # Don’t animate opening applications from the Dock
        defaults write com.apple.dock launchanim -bool false

        # Speed up Mission Control animations
        defaults write com.apple.dock expose-animation-duration -float 0.1

        # Disable Dashboard
        defaults write com.apple.dashboard mcx-disabled -bool true

        # Don’t show Dashboard as a Space
        defaults write com.apple.dock dashboard-in-overlay -bool true

        # Don’t automatically rearrange Spaces based on most recent use
        defaults write com.apple.dock mru-spaces -bool false

        # Remove the auto-hiding Dock delay
        defaults write com.apple.dock autohide-delay -float 0

        # Remove the animation when hiding/showing the Dock
        defaults write com.apple.dock autohide-time-modifier -float 0

        # Automatically hide and show the Dock
        defaults write com.apple.dock autohide -bool true

        # Don't make Dock icons of hidden applications translucent
        defaults write com.apple.dock showhidden -bool false

        ###############################################################################
        # Safari & WebKit                                                             #
        ###############################################################################

        # Privacy: don’t send search queries to Apple
        defaults write com.apple.Safari UniversalSearchEnabled -bool false
        defaults write com.apple.Safari SuppressSearchSuggestions -bool true

        # Press Tab to highlight each item on a web page
        defaults write com.apple.Safari WebKitTabToLinksPreferenceKey -bool true
        defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks -bool true

        # Show the full URL in the address bar (note: this still hides the scheme)
        defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true

        # Set Safari’s home page to `about:blank` for faster loading
        defaults write com.apple.Safari HomePage -string "about:blank"

        # Prevent Safari from opening ‘safe’ files automatically after downloading
        defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

        # Enable Safari’s debug menu
        defaults write com.apple.Safari IncludeInternalDebugMenu -bool true

        # Enable the Develop menu and the Web Inspector in Safari
        defaults write com.apple.Safari IncludeDevelopMenu -bool true
        defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
        defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

        # Add a context menu item for showing the Web Inspector in web views
        defaults write NSGlobalDomain WebKitDeveloperExtras -bool true

        ###############################################################################
        # Mail                                                                        #
        ###############################################################################

        # Disable send and reply animations in Mail.app
        defaults write com.apple.mail DisableReplyAnimations -bool true
        defaults write com.apple.mail DisableSendAnimations -bool true

        # Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
        defaults write com.apple.mail AddressesIncludeNameOnPasteboard -bool false

        ###############################################################################
        # Terminal & iTerm 2                                                          #
        ###############################################################################

        # Only use UTF-8 in Terminal.app
        defaults write com.apple.terminal StringEncodings -array 4

        # Don’t display the annoying prompt when quitting iTerm
        defaults write com.googlecode.iterm2 PromptOnQuit -bool false

        ###############################################################################
        # Time Machine                                                                #
        ###############################################################################

        # Prevent Time Machine from prompting to use new hard drives as backup volume
        defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

        ###############################################################################
        # Google Chrome                                                               #
        ###############################################################################

        # Use the system-native print preview dialog
        defaults write com.google.Chrome DisablePrintPreview -bool true

        # Expand the print dialog by default
        defaults write com.google.Chrome PMPrintingExpandedStateForPrint2 -bool true

        ###############################################################################
        # Kill affected applications                                                  #
        ###############################################################################

        for app in "cfprefsd" "Dock" "Finder" "Google Chrome" \
            "Mail" "Safari" "SystemUIServer" "Terminal" ; do
        killall "${app}" > /dev/null 2>&1
    done

    # Set hostname
    source $DIR/rename
    # Install applications using brew
    source $DIR/brew-apps
    # Link dotfiles using RCM and load new config
    echo -e "\nLinking dotfiles to your home directory ..."
    rcup -v -d ~/.dotfiles -x "*:*osx*" -x "*:*linux*" -x "*:*README*"
    source ~/.bashrc

    # Setup Vim
    echo -e "\nSetting up Vim ..."
    if [ ! -d ~/.vim/bundle/base16-vim ]; then
        git clone https://github.com/chriskempson/base16-vim.git ~/.vim/bundle/base16-vim
    fi
    if [ ! -d ~/.vim/bundle/Vundle.vim ]; then
        git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
    fi
    vim +PluginInstall +qall

    echo -e "\nDone. Note that some of these changes require a logout/restart to take effect."
else
    echo "This script runs under OS X only."
fi
